jobs:
  include:
    - os: linux
      dist: xenial
      language: python
      python: 3.6
      env: TOXENV=py36
    - os: linux
      dist: bionic
      language: python
      python: 3.8
      env: TOXENV=py38
    - os: osx
      env:
        - TOXENV=py38
        - PYTHON_BREW_VERSION=python@3.8
install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install $PYTHON_BREW_VERSION; fi
  - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
  - source ~/.profile
  - poetry install
script:
  - poetry run pip --disable-pip-version-check install poetry
  - poetry run tox
after_success:
  - coveralls