---
    image:
      - Visual Studio 2019
    environment:
      matrix:
      - PYTHON_EXECUTABLE: C:\Python36\python.exe
      - PYTHON_EXECUTABLE: C:\Python36-x64\python.exe
      - PYTHON_EXECUTABLE: C:\Python38\python.exe
      - PYTHON_EXECUTABLE: C:\Python38-x64\python.exe

    build: off

    install:
      - ps: bin/install_poetry.ps1
      - ps: bin/refresh_path.ps1
      - ps: bin/install_dependencies.ps1

    test_script:
      - ps: run_tox.ps1
