---
    image:
      - Visual Studio 2019
    configuration:
      - Python36_32
      - Python36_64
      - Python38_32
      - Python38_64
    for:
      -
        matrix:
          only:
            - configuration: Python36_32
        environment:
          PYTHON_EXECUTABLE: C:\Python36\python.exe
          TOXENV: py36
      -
        matrix:
          only:
            - configuration: Python36_64
        environment:
          PYTHON_EXECUTABLE: C:\Python36-x64\python.exe
          TOXENV: py36
      -
        matrix:
          only:
            - configuration: Python38_32
        environment:
          PYTHON_EXECUTABLE: C:\Python38\python.exe
          TOXENV: py38
      -
        matrix:
          only:
            - configuration: Python38_64
        environment:
          PYTHON_EXECUTABLE: C:\Python38-x64\python.exe
          TOXENV: py38

    build: off

    install:
      - ps: bin/install_poetry.ps1
      - ps: bin/refresh_path.ps1
      - ps: bin/install_dependencies.ps1

    test_script:
      - ps: bin/run_tox.ps1

    after_test:
      - ps: bin/build.ps1

    notifications:
      - provider: Slack
        auth_token:
          secure: mYhZ3VvMr3r7bZ6O2kCCQ61KB3R2UAA2X1KyoC+ZiHaA848Fykh24Tx0Ic9i3Ztsjkj0mmQ7erX5JniAMoP+Lg==
        channel: '#odyssey_build_notifications'
