---
    image:
      - Visual Studio 2019
    environment:
      matrix:
      - PYTHON_EXECUTABLE: C:\Python36\python.exe
      - PYTHON_EXECUTABLE: C:\Python36-x64\python.exe
      - PYTHON_EXECUTABLE: C:\Python38\python.exe
      - PYTHON_EXECUTABLE: C:\Python38-x64\python.exe

    build: off

    install:
      - ps: Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing -OutFile get-poetry.py; & $Env:PYTHON_EXECUTABLE get-poetry.py --yes; Remove-Item get-poetry.py;
      - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User");
      - ps: poetry env use $Env:PYTHON_EXECUTABLE;
      - ps: poetry install;

    test_script:
      - ps: poetry run pip --disable-pip-version-check install poetry
      - ps: poetry run tox
