---
    environment:
      matrix:
      - TOXENV: py36
      - TOXENV: py38

    build: off

    install:
      - ps: |
        (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python;
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User");
        poetry install;

    test_script:
      - ps: |
        poetry run pip install poetry
        poetry run tox
