[tool.poetry]
name = "odyssey"
version = "0.1.0"
description = ""
readme = "README.rst"
license = "MIT"
authors = ["Justin Sharma <justin.elite@gmail.com>"]
packages = [
    { include = "odyssey", from = "src" },
]

[tool.poetry.scripts]
odyssey = 'odyssey.__main__:main'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
