[tool.poetry]
name = "odyssey"
version = "0.1.0"
description = ""
readme = "README.rst"
license = "MIT"
authors = ["Justin Sharma <justin.elite@gmail.com>"]
packages = [
    { include = "odyssey", from = "src" },
]

[tool.poetry.scripts]
odyssey = 'odyssey.__main__:main'

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.4.2"
sphinx = "^3.0.3"
black = "^19.10b0"
flake8 = "^3.8.2"
pylint = "^2.5.2"
tox = "^3.15.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
