version: 2.1

orbs:
  python: circleci/python@1.3.2
  slack: circleci/slack@3.4.2

jobs:
  build-and-test-3-6-12:
    docker:
      - image: circleci/python:3.6.12-buster
    steps:
      - checkout
      - run:
          name: Install rust
          command: sudo curl https://sh.rustup.rs -sSf | sudo sh -s -- -y
      - run:
          name: Install poetry
          command: bin/install_poetry.sh
      - run:
          name: Install dependencies
          command: bin/install_dependencies.sh
      - run:
          name: Run pytest
          command: bin/run_pytest.sh
      - run:
          name: Build binaries
          command: bin/build.sh
      - run:
          name: Build executable
          command: bin/build_executable.sh
      - slack/status
  build-and-test-3-8-7:
    docker:
      - image: circleci/python:3.8.7-buster
    steps:
      - checkout
      - run:
          name: Install rust
          command: sudo curl https://sh.rustup.rs -sSf | sudo sh -s -- -y
      - run:
          name: Install poetry
          command: bin/install_poetry.sh
      - run:
          name: Install dependencies
          command: bin/install_dependencies.sh
      - run:
          name: Run pytest
          command: bin/run_pytest.sh
      - run:
          name: Build binaries
          command: bin/build.sh
      - run:
          name: Build executable
          command: bin/build_executable.sh
      - slack/status
workflows:
  main:
    jobs:
      - build-and-test-3-6-12
      - build-and-test-3-8-7
