version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@3.4.2

jobs:
  build-and-test-3-6-9:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - run: 
          name: "Set environment variables"
          command: echo 'export TOXENV=py36' >> $BASH_ENV
      - run:
          name: Install poetry
          command: bin/install_poetry.sh
      - run:
          name: Install dependencies
          command: bin/install_dependencies.sh
      - run:
          name: Run tox
          command: bin/run_pytest.sh
      - run:
          name: Build binaries
          command: bin/build.sh
      - run:
          name: Build executable
          command: bin/build_executable.sh
      - slack/status
  build-and-test-3-8-2:
    docker:
      - image: circleci/python:3.8.2
    steps:
      - checkout
      - run: 
          name: "Set environment variables"
          command: echo 'export TOXENV=py38' >> $BASH_ENV
      - run:
          name: Install poetry
          command: bin/install_poetry.sh
      - run:
          name: Install dependencies
          command: bin/install_dependencies.sh
      - run:
          name: Run tox
          command: bin/run_pytest.sh
      - run:
          name: Build binaries
          command: bin/build.sh
      - run:
          name: Build executable
          command: bin/build_executable.sh
      - slack/status
workflows:
  main:
    jobs:
      - build-and-test-3-6-9
      - build-and-test-3-8-2
