name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        . bin/install_poetry.sh
        bin/install_dependencies.sh
        bin/run_pytest.sh
        bin/build.sh
        bin/build_executable.sh
