name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        . bin/install_poetry.sh
        bin/install_dependencies.sh
        bin/run_pytest.sh
        bin/build.sh
        bin/build_executable.sh

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - uses: rtCamp/action-slack-notify@master
        env:
          SLACK_ICON: https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-12-19/288981919427_f45f04edd92902a96859_512.png
          SLACK_CHANNEL: odyssey_build_notifications
          SLACK_MESSAGE: Commit Message - ${{ github.event.commits[0].message }}
          SLACK_COLOR: ${{job.status}}
          SLACK_TITLE: Github Build ${{job.status}}
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
